In [2]:
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image

1.Sort

In [17]:
init_arr = np.array([0,3,0,1,1,2,1,0,2,1])
print("Initial array:",init_arr)
un_arr,fr_arr = np.unique(init_arr,return_counts = True)
id_arr = np.argsort(fr_arr)
print("Sorted array by frequence:",un_arr[id_arr])

Initial array: [0 3 0 1 1 2 1 0 2 1]
Sorted array by frequence: [3 2 0 1]


2.Unique colors

In [85]:
img = Image.open("image.jpg")
color_arr = np.array(img, dtype = np.uint8)
new_arr = color_arr.reshape(-1, color_arr.shape[2])
un_arr = np.unique(new_arr,axis = 0)
print(un_arr.size / 3)

23142.0


3.Vector

In [26]:
def Mov_avg(arr,dx):# dx - количество соседей с одной стороны
    mov_avg = np.zeros(arr.size)
    i = 0
    while i < arr.size:
        if i - dx < 0:
            mov_avg[i] = 1.0 * arr[0:i + dx + 1].sum() / (2 * dx + 1)
        elif i + dx > arr.size - 1:
            mov_avg[i] = 1.0 * arr[i - dx:arr.size].sum() / (2 * dx + 1)
        else:
            mov_avg[i] = arr[i - dx:i + dx + 1].mean()
        i = i + 1
    return mov_avg

arr = np.array([3,1,0,2])
print(Mov_avg(arr,1))

[1.33333333 1.33333333 1.         0.66666667]


4.Triangle

In [109]:
def isTriangle(a):
    if a[0] > 0 and a[1] > 0 and a[2] > 0:
        if a[0] <= a[1] + a[2] and a[1] <= a[2] + a[0] and a[2] <= a[1] + a[0]:
            print(a,"is triagle")
        else:
            print(a,"is not triagle")
    else:
        print(a,"is not triagle")
matr = np.array([[1,1,1],[3,4,5],[0,1,100]])
empt_mass = np.apply_along_axis(isTriangle,axis = 1,arr = matr)

[1 1 1] is triagle
[3 4 5] is triagle
[  0   1 100] is not triagle
